apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hivebox-ingress
  namespace: hivebox
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: hivebox.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hivebox-service
                port:
                  number: 80



# >minikube ssh
# >cat /etc/hosts
# >sudo /bin/sh -c 'echo "<minikube ip> hivebox.local" >> /etc/hosts'
# >hivebox.local
# add it to the /etc/hosts of your local machine too
# >minikube tunnel